### ISSUE TITLE
value.track is null

### ISSUE THREAD

**Issue by grefab** [secuvera/SpotMyBackup#7]
After 132 playlists and 6637 tracks (which might be all) loading stops. Page still shows: 
`Please wait. Loading your playlists and tracks ...`

DevConsole printed following error upon stopping:
`TypeError: value.track is null[Weitere Informationen]  www.spotmybackup.com:658:32`
`	success/< http://www.spotmybackup.com/:658:32`
`	each https://code.jquery.com/jquery-1.11.2.min.js:2:2973`
`	success http://www.spotmybackup.com/:657:17`
`	j https://code.jquery.com/jquery-1.11.2.min.js:2:27290`
`	fireWith https://code.jquery.com/jquery-1.11.2.min.js:2:28108`
`	x https://code.jquery.com/jquery-1.11.2.min.js:4:22059`
`	b https://code.jquery.com/jquery-1.11.2.min.js:4:25980`

**Comment by secuvera** [comment]
Hi, i looked into your debug output and you are correct. The hosted version was not up to date. The fix provided by fcingolani should handle this issue. I updated the hosted version. Let me know if it works for you now.

**Comment by grefab** [comment]
Hey, thanks for looking after this issue! However, I got the same problem like mentioned in #8. I thought it would only be a temporary issue but persists for almost a week now. Therefore I cannot verify if the issue is fixed.

**Comment by secuvera** [comment]
After loading the page, press Strg+F5 (english: Crtl+F5). If that fixes the issue i might know what i need to do ^^

**Comment by grefab** [comment]
Yep, works now. Thanks! :)
